project_id = "dfzuijskqjbtpckzzemh"

[functions.extension-data-bridge]
verify_jwt = false

[functions.check-ssl]
verify_jwt = false

[functions.check-accessibility]
verify_jwt = false

[functions.google-places-proxy]
verify_jwt = false

[functions.google-pagespeed-proxy]
verify_jwt = false

[functions.google-nearby-proxy]
verify_jwt = false

[functions.google-search-proxy]
verify_jwt = false

[functions.check-safe-browsing]
verify_jwt = false

[functions.detect-cookie-banner]
verify_jwt = false